library: bts
library_options:
    encoder: 'densenet161_bts'
    checkpoint: 'bts_nyu_v2_pytorch_densenet161'
    bts_size: 512
    max_depth: 10 # meters
    image_shape:
        width: 640
        height: 480
